language: python
python:
  - "2.7"
  - "3.3"
env:
  - KAZOO_VERSION=1.3
  - KAZOO_VERSION=2.0
install:
  - pip install kazoo==$KAZOO_VERSION
  - make zookeeper
  - pip freeze
script: make integration
